### ISSUE TITLE
[iOS] Folders don't respect the `Automatically Download Article` setting

### ISSUE THREAD

**Issue by michalcs** [anyboxhq/bug-reports-anybox#2]
```
iPhone 14 Pro
iOS 17.1
Anybox 2.1.2 (190)
```

## Steps 

1. in Anybox, create a folder `Read` let's say and enable `Automatically Download Article`
2. in Safari, navigate to any page, let's say this [random from wikipedia](https://en.m.wikipedia.org/wiki/Rodrigues_night_heron)
	- tap `Share` and select the Anybox icon
	- in the Save sheet, tap `Move to Folder…` and select `Read` (the one created in previous step)
	- tap `Save`
3. switch back to Anybox and navigate to the `Read` folder view

## Expected

The article should auto-download

## Actual

The article never downloads, unless triggered manually

## Notes

- This occurs only on iOS, working as expected on Mac.
- This occurs only in Folders, Tags working as expected on both iOS and Mac

**Comment by francisfeng** [comment]
This should be fixed in version 2.1.3.

**Comment by michalcs** [comment]
Thanks for looking into this. Unfortunately the issue still persists in 2.1.4 (210). For existing and new folders too.

**Comment by michalcs** [comment]
Thanks for looking into this. The issue is no longer reproducible in 2.1.4 (210) 🎉
